In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from imblearn.over_sampling import ADASYN

In [6]:
df = pd.read_csv('cleaned-outcomes-no-hypertension.csv')
df.drop('Unnamed: 0', axis=1, inplace=True)
pd.set_option('display.max_columns', None)
df.head()

,30850-0.0,30780-0.0,30690-0.0,1488-0.0,30790-0.0,1418-0.0,1329-0.0,4079-0.0,1220-0.0,23101-0.0,1428-0.0,1249-0.0,1349-0.0,23099-0.0,48-0.0,1369-0.0,23100-0.0,20117-0.0,1299-0.0,2100-0.0,21003-0.0,30710-0.0,1160-0.0,30760-0.0,1438-0.0,2654-0.0,4080-0.0,30640-0.0,1339-0.0,30750-0.0,21000-0.0,2050-0.0,1408-0.0,49-0.0,1200-0.0,30770-0.0,1538-0.0,1458-0.0,31-0.0,1528-0.0,1319-0.0,30740-0.0,6138-0.0,1359-0.0,1389-0.0,1478-0.0,2090-0.0,1508-0.0,845-0.0,1379-0.0,6142-0.0,1468-0.0,1289-0.0,1548-0.0,30630-0.0,30870-0.0,1239-0.0,21001-0.0,1309-0.0,1448-0.0,hypertension,outcome_cardiomyopathies,outcome_ischemic_heart_disease,outcome_heart_failure,outcome_myocardial_infarction,outcome_peripheral_vascular_disease,outcome_cardiac_arrest,outcome_cerebral_infarction,outcome_arrhythmia,multi-labels,age,gender,race
0,-1.279446,0.552978,0.856104,0.772987,0.160138,3,2,-0.492958,0,-0.947164,0,1,1,0.483027,-1.545793,1,-0.138009,2,3.546199,1,-0.948313,-0.555101,-0.139039,0.933693,-0.377692,6,-1.665131,0.850258,2,-0.362231,1001,2,1,-0.312803,3,0.981135,2,-0.255880,0,-0.343536,-0.449755,0.177819,1,2,1,1,1,3,5.996074,1,1,3,1.565603,2,0.403095,-0.842728,0,-0.788176,-0.168110,3,0,0,0,0,0,0,0,0,1,"[0, 0, 0, 0, 0, 0, 0, 1]",54,Female,British
1,0.868954,0.158768,0.079159,-0.539868,-0.613795,2,2,0.775257,0,1.556107,1,1,4,0.588425,1.771461,2,1.617787,2,-0.084622,0,0.652782,0.157478,1.470442,-0.491565,-0.154516,7,1.106447,0.080170,2,0.319113,1001,1,3,0.796999,2,-1.715852,0,0.827023,1,-0.117632,-0.449755,-0.173128,3,3,1,1,0,2,-0.172754,2,1,5,-0.425927,2,-0.356404,0.428763,0,1.257227,-0.753584,1,1,0,1,0,1,0,0,0,0,"[1, 0, 1, 0, 0, 0, 0, 0]",65,Male,British
2,0.541023,0.331835,0.296342,-1.196296,-0.297654,2,1,1.499951,0,1.309186,0,1,2,-0.207912,1.194547,1,0.381864,2,-0.084622,0,-0.802759,-0.090479,-0.139039,0.007462,-0.377692,7,-0.427819,0.328844,2,5.310474,1001,1,2,0.191652,2,-0.231662,1,0.827023,1,-0.343536,-0.449755,5.453302,3,3,2,1,0,2,1.973672,2,1,4,0.071956,2,0.277348,0.334732,0,0.421573,-0.753584,3,1,0,1,0,0,0,1,1,1,"[0, 0, 1, 0, 0, 1, 1, 1]",55,Male,British
3,-1.060849,-0.519316,0.121831,-1.196296,-0.146259,2,2,-1.036478,0,-1.372890,0,4,1,-0.196202,-2.050592,2,-0.922722,2,1.276936,0,-1.676084,-0.450193,0.665702,2.027372,0.068661,7,-1.368176,-0.758102,2,-0.200820,1002,1,2,-1.422604,1,1.900884,2,0.095332,0,0.108272,0.065754,-0.311660,6,2,2,1,0,2,0.685816,2,1,3,1.067720,2,1.518025,-0.677001,0,-1.532064,-0.753584,3,0,0,0,0,0,0,0,0,1,"[0, 0, 0, 0, 0, 0, 0, 1]",49,Female,Irish
4,-1.237093,-0.751772,-0.590704,1.101201,-0.822833,3,2,-0.855305,1,-0.836475,1,4,1,-0.161069,-0.752536,1,-0.628455,2,0.823084,0,0.070565,-0.586771,-0.139039,0.364125,-1.270397,7,-1.516654,-1.066939,3,-0.455010,1001,1,3,-0.010130,1,3.718133,0,0.827023,0,0.560080,0.581263,-0.166356,3,3,1,2,0,1,-0.172754,1,1,4,0.071956,2,1.435715,-0.198236,0,-0.516107,0.417365,3,1,0,0,0,1,0,0,0,0,"[1, 0, 0, 0, 0, 0, 0, 0]",61,Female,British

In [9]:
X = df.loc[:,:'hypertension']
y = df.loc[:,'outcome_cardiomyopathies']

In [11]:
X_resampled, y_resampled = ADASYN().fit_resample(X, y)

In [15]:
print(len(X))
print(len(X_resampled))
print(y.value_counts())
print(y_resampled.value_counts())

26551
50766
0    25494
1     1057
Name: outcome_cardiomyopathies, dtype: int64
0    25494
1    25272
Name: outcome_cardiomyopathies, dtype: int64